[build]
command = "pip install virtualenv && virtualenv venv && source venv/bin/activate && pip install -r requirements.txt && python app.py"
publish = "."

[build.environment]
FLASK_APP = "app.py"
FLASK_ENV = "production"
