[build]
command = "pip install virtualenv && virtualenv venv && . venv/bin/activate && pip install -r requirements.txt"
publish = "."

[build.environment]
FLASK_APP = "app.py"
FLASK_ENV = "production"
